apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tekton-pipelines
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: index.docker.io/nginx:1.15.12-alpine
        ports:
        - containerPort: 80
